# Generated by Django 5.1.6 on 2025-03-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kudos_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
